// src/components/AppWrapper.tsx
"use client";

import { cn } from "@/utils/helpers";
import dynamic from "next/dynamic";
import type { FunctionComponent, ReactNode } from "react";

type WrapperProps = {
  className?: string;
  dotsClassName?: string;
  children?: ReactNode;
};

const DotsDynamic = dynamic(() => import("@/components/Dots"), { ssr: false });

const AppWrapper: FunctionComponent<WrapperProps> = ({
  children,
  className,
  dotsClassName,
}: WrapperProps) => {
  return (
    <main
      className={cn("relative min-h-screen bg-black text-zinc-50", className)}
    >
      <DotsDynamic className={dotsClassName} />
      {children}
    </main>
  );
};

export default AppWrapper;

// web/src/lib/components/AppWrapper.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { Snippet } from "svelte";
  import Dots from "./Dots.svelte";

  let {
    class: className = "",
    backgroundClass = "",
    children,
  }: {
    class?: string;
    backgroundClass?: string;
    children?: Snippet;
  } = $props();
</script>

<div class="pointer-events-none fixed inset-0 -z-20 bg-black"></div>
<Dots class={[backgroundClass]} />
<main class={cn("relative min-h-screen text-zinc-50", className)}>
  {#if children}
    {@render children()}
  {/if}
</main>
